apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: efklog
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>

    <match kubernetes.**>
      @type elasticsearch
      @id elasticsearch
      host elasticsearch
      port 9200
      logstash_format true
      include_tag_key true
      logstash_prefix infra360.io
      logstash_dateformat %Y-%m-%d
      type_name _doc
      logstash_prefix_separator -
    </match>
